export const FakeData = [
  {
    id: 1,
    name: "Complete Project Proposal",
    content:
      "Finish writing the Q2 project proposal and submit to management for review.",
    modifiedDate: "2025-05-20",
    color: "bg-red-500",
    sortId: 1,
  },
  {
    id: 2,
    name: "Buy Groceries",
    content: "Pick up milk, bread, eggs, and vegetables for the week.",
    modifiedDate: "2025-05-22",
    color: "bg-green-500",
    sortId: 2,
  },
  {
    id: 3,
    name: "Schedule Doctor Appointment",
    content: "Call Dr. Smith's office to schedule annual checkup.",
    modifiedDate: "2025-05-18",
    color: "bg-blue-500",
    sortId: 3,
  },
  {
    id: 4,
    name: "Learn React Native",
    content: "Complete the React Native tutorial series on mobile development.",
    modifiedDate: "2025-05-25",
    color: "bg-purple-500",
    sortId: 4,
  },
  {
    id: 5,
    name: "Clean the Garage",
    content: "Organize tools, donate unused items, and sweep the floor.",
    modifiedDate: "2025-05-15",
    color: "bg-yellow-500",
    sortId: 5,
  },
  {
    id: 6,
    name: "Plan Birthday Party",
    content: "Organize surprise party for Sarah's 30th birthday next month.",
    modifiedDate: "2025-05-23",
    color: "bg-pink-500",
    sortId: 6,
  },
  {
    id: 7,
    name: "Fix Leaky Faucet",
    content: "Replace the washer in the kitchen sink faucet.",
    modifiedDate: "2025-05-19",
    color: "bg-orange-500",
    sortId: 7,
  },
  {
    id: 8,
    name: "Read 'The Pragmatic Programmer'",
    content:
      "Finish reading chapters 5-8 of the programming best practices book.",
    modifiedDate: "2025-05-21",
    color: "bg-indigo-500",
    sortId: 8,
  },
  {
    id: 9,
    name: "Update LinkedIn Profile",
    content: "Add recent project experience and update skills section.",
    modifiedDate: "2025-05-24",
    color: "bg-cyan-500",
    sortId: 9,
  },
  {
    id: 10,
    name: "Plant Garden Vegetables",
    content: "Plant tomatoes, peppers, and herbs in the backyard garden.",
    modifiedDate: "2025-05-17",
    color: "bg-emerald-500",
    sortId: 10,
  },
  {
    id: 11,
    name: "Backup Computer Files",
    content:
      "Create backup of important documents and photos to external drive.",
    modifiedDate: "2025-05-16",
    color: "bg-slate-500",
    sortId: 11,
  },
  {
    id: 12,
    name: "Call Mom and Dad",
    content: "Weekly check-in call with parents to catch up on family news.",
    modifiedDate: "2025-05-25",
    color: "bg-rose-500",
    sortId: 12,
  },
  {
    id: 13,
    name: "Research Vacation Destinations",
    content: "Look into travel options for summer vacation in Europe.",
    modifiedDate: "2025-05-22",
    color: "bg-teal-500",
    sortId: 13,
  },
  {
    id: 14,
    name: "Organize Digital Photos",
    content: "Sort and organize photo library by year and create albums.",
    modifiedDate: "2025-05-20",
    color: "bg-violet-500",
    sortId: 14,
  },
  {
    id: 15,
    name: "Start Morning Exercise Routine",
    content: "Begin 30-minute morning workout routine for better health.",
    modifiedDate: "2025-05-24",
    color: "bg-amber-500",
    sortId: 15,
  },
];
